# Site settings
title: Mirror.JeffreyDinackus.com
author:
  name: JMirror
  email: your-email@domain.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
